/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-tint": "#006c4e",
        "tertiary": "#855000",
        "surface-container-low": "#f6f4eb",
        "primary-fixed": "#86f8c9",
        "secondary": "#2a6959",
        "on-secondary-fixed": "#002019",
        "on-primary": "#ffffff",
        "secondary-fixed": "#b0efdb",
        "outline": "#6d7a73",
        "inverse-primary": "#68dbae",
        "error": "#ba1a1a",
        "surface-container-highest": "#e5e2da",
        "surface": "#fcf9f1",
        "error-container": "#ffdad6",
        "surface-container-high": "#eae8e0",
        "on-error-container": "#93000a",
        "tertiary-container": "#a76500",
        "surface-bright": "#fcf9f1",
        "inverse-on-surface": "#f3f1e8",
        "on-secondary-fixed-variant": "#095041",
        "primary": "#00694c",
        "on-background": "#1c1c17",
        "surface-container": "#f0eee5",
        "on-tertiary": "#ffffff",
        "on-primary-container": "#f5fff7",
        "on-primary-fixed-variant": "#00513a",
        "outline-variant": "#bccac1",
        "tertiary-fixed": "#ffdcbb",
        "on-tertiary-container": "#fffbff",
        "background": "#fcf9f1",
        "on-surface": "#1c1c17",
        "secondary-container": "#adedd8",
        "on-tertiary-fixed": "#2b1700",
        "inverse-surface": "#31312b",
        "on-tertiary-fixed-variant": "#673d00",
        "primary-fixed-dim": "#68dbae",
        "on-secondary-container": "#2f6d5d",
        "primary-container": "#008560",
        "on-secondary": "#ffffff",
        "surface-container-lowest": "#ffffff",
        "on-error": "#ffffff",
        "on-surface-variant": "#3d4943",
        "on-primary-fixed": "#002115",
        "secondary-fixed-dim": "#94d3bf",
        "surface-variant": "#e5e2da",
        "tertiary-fixed-dim": "#ffb869",
        "surface-dim": "#dcdad2"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Inter"],
        "body": ["Inter"],
        "label": ["Inter"],
        "inter": ["Inter"],
      }
    },
  },
  plugins: [],
}
